name: Zip and Attach to Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ZIP archive
        run: |
          zip -r extensionmanager.blueprint . -x "*.git*" "*node_modules*" ".editorconfig"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            extensionmanager.blueprint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
